name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: pytest

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.0.0

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Terraform Init
      working-directory: ./terraform/aws
      run: terraform init

    - name: Terraform Plan
      working-directory: ./terraform/aws
      run: terraform plan

    - name: Terraform Apply
      working-directory: ./terraform/aws
      run: terraform apply -auto-approve

    - name: Get Lambda Function URL
      working-directory: ./terraform/aws
      run: |
        echo "API Gateway URL: $(terraform output -raw api_gateway_url)" >> $GITHUB_STEP_SUMMARY
        echo "Lambda Function ARN: $(terraform output -raw lambda_function_arn)" >> $GITHUB_STEP_SUMMARY 